library(caret)
wolf_present=factor(c("no","yes","yes"))
cried_wolf=factor(c("yes","yes","no"))
cat("Actual Values: ",wolf_present,"\n")
cat("Predicted Values: ",cried_wolf,"\n")
confusion_matrix=table(wolf_present,cried_wolf,dnn=c("Actual","Predicted"))
cm=confusionMatrix(data=cried_wolf,reference=wolf_present)
print(confusion_matrix)
print(cm)