F_min=50000
F_max=100000
F=80000
v=(F - F_min)/(F_max - F_min)
cat("a)Min-Max Normalization= ",v,"\n")
data=c(200,300,400,600,1000)
min_val=min(data)
max_val=max(data)
Min_max_normalized_data=(data - min_val)/(max_val - min_val)*(1-0)+0
cat("b)\n","a)Min_Max Normalized data= ",Min_max_normalized_data,"\n")
mean_val=mean(data)
sd_val=sd(data)
normalized_data=(data - mean_val)/sd_val
cat("b)Z score Normalized data= ",normalized_data)
